name: Branch

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'
      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set extra GitHub environment variables
        id: github-env-vars
        uses: rlespinasse/github-slug-action@v4

      - name: Checkout source
        id: checkout-source
        uses: actions/checkout@v4

      - name: Schema Validation
        id: schema-validation
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          files: 'action.yaml'
          schema: https://json.schemastore.org/github-action.json